// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apikey.proto

package com.nordstrom.gtm.apikey;

public interface ApiKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apikey.ApiKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service_name = 1;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>string service_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string key_name = 2;</code>
   */
  java.lang.String getKeyName();
  /**
   * <code>string key_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyNameBytes();

  /**
   * <code>string key = 3;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 3;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
