// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apikey.proto

package com.nordstrom.gtm.apikey;

public final class ApiKeyProto {
  private ApiKeyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apikey_KeyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apikey_KeyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apikey_ApiKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apikey_ApiKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apikey_ApiKeyList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apikey_ApiKeyList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apikey_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apikey_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014apikey.proto\022\006apikey\"\230\001\n\nKeyRequest\022\024\n" +
      "\014service_name\030\001 \001(\t\022\020\n\010key_name\030\002 \001(\t\022\r\n" +
      "\005three\030\003 \001(\t\022\014\n\004four\030\004 \001(\t\022\014\n\004five\030\005 \001(\t" +
      "\022\013\n\003six\030\006 \001(\t\022\r\n\005seven\030\007 \001(\t\022\r\n\005eight\030\010 " +
      "\001(\t\022\014\n\004nine\030\t \001(\t\"=\n\006ApiKey\022\024\n\014service_n" +
      "ame\030\001 \001(\t\022\020\n\010key_name\030\002 \001(\t\022\013\n\003key\030\003 \001(\t" +
      "\")\n\nApiKeyList\022\033\n\003key\030\001 \003(\0132\016.apikey.Api" +
      "Key\"\007\n\005Empty2\257\001\n\010ApiKeyer\0229\n\021GenerateNew" +
      "ApiKey\022\022.apikey.KeyRequest\032\016.apikey.ApiK" +
      "ey\"\000\022/\n\014RevokeApiKey\022\016.apikey.ApiKey\032\r.a" +
      "pikey.Empty\"\000\0227\n\013ListApiKeys\022\022.apikey.Ke" +
      "yRequest\032\022.apikey.ApiKeyList\"\000B)\n\030com.no" +
      "rdstrom.gtm.apikeyB\013ApiKeyProtoP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_apikey_KeyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_apikey_KeyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apikey_KeyRequest_descriptor,
        new java.lang.String[] { "ServiceName", "KeyName", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", });
    internal_static_apikey_ApiKey_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_apikey_ApiKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apikey_ApiKey_descriptor,
        new java.lang.String[] { "ServiceName", "KeyName", "Key", });
    internal_static_apikey_ApiKeyList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_apikey_ApiKeyList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apikey_ApiKeyList_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_apikey_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_apikey_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apikey_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
