// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apikey.proto

package com.nordstrom.gtm.apikey;

public interface ApiKeyListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apikey.ApiKeyList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .apikey.ApiKey key = 1;</code>
   */
  java.util.List<com.nordstrom.gtm.apikey.ApiKey> 
      getKeyList();
  /**
   * <code>repeated .apikey.ApiKey key = 1;</code>
   */
  com.nordstrom.gtm.apikey.ApiKey getKey(int index);
  /**
   * <code>repeated .apikey.ApiKey key = 1;</code>
   */
  int getKeyCount();
  /**
   * <code>repeated .apikey.ApiKey key = 1;</code>
   */
  java.util.List<? extends com.nordstrom.gtm.apikey.ApiKeyOrBuilder> 
      getKeyOrBuilderList();
  /**
   * <code>repeated .apikey.ApiKey key = 1;</code>
   */
  com.nordstrom.gtm.apikey.ApiKeyOrBuilder getKeyOrBuilder(
      int index);
}
