// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apikey.proto

package com.nordstrom.gtm.apikey;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apikey.Empty)
    com.google.protobuf.MessageOrBuilder {
}
