// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apikey.proto

package com.nordstrom.gtm.apikey;

public interface KeyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apikey.KeyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service_name = 1;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>string service_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string key_name = 2;</code>
   */
  java.lang.String getKeyName();
  /**
   * <code>string key_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyNameBytes();

  /**
   * <code>string three = 3;</code>
   */
  java.lang.String getThree();
  /**
   * <code>string three = 3;</code>
   */
  com.google.protobuf.ByteString
      getThreeBytes();

  /**
   * <code>string four = 4;</code>
   */
  java.lang.String getFour();
  /**
   * <code>string four = 4;</code>
   */
  com.google.protobuf.ByteString
      getFourBytes();

  /**
   * <code>string five = 5;</code>
   */
  java.lang.String getFive();
  /**
   * <code>string five = 5;</code>
   */
  com.google.protobuf.ByteString
      getFiveBytes();

  /**
   * <code>string six = 6;</code>
   */
  java.lang.String getSix();
  /**
   * <code>string six = 6;</code>
   */
  com.google.protobuf.ByteString
      getSixBytes();

  /**
   * <code>string seven = 7;</code>
   */
  java.lang.String getSeven();
  /**
   * <code>string seven = 7;</code>
   */
  com.google.protobuf.ByteString
      getSevenBytes();

  /**
   * <code>string eight = 8;</code>
   */
  java.lang.String getEight();
  /**
   * <code>string eight = 8;</code>
   */
  com.google.protobuf.ByteString
      getEightBytes();

  /**
   * <code>string nine = 9;</code>
   */
  java.lang.String getNine();
  /**
   * <code>string nine = 9;</code>
   */
  com.google.protobuf.ByteString
      getNineBytes();
}
