// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apikey.proto

package com.nordstrom.gtm.apikey;

/**
 * Protobuf type {@code apikey.KeyRequest}
 */
public  final class KeyRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:apikey.KeyRequest)
    KeyRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KeyRequest.newBuilder() to construct.
  private KeyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KeyRequest() {
    serviceName_ = "";
    keyName_ = "";
    three_ = "";
    four_ = "";
    five_ = "";
    six_ = "";
    seven_ = "";
    eight_ = "";
    nine_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private KeyRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            serviceName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            keyName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            three_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            four_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            five_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            six_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            seven_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            eight_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            nine_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nordstrom.gtm.apikey.ApiKeyProto.internal_static_apikey_KeyRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nordstrom.gtm.apikey.ApiKeyProto.internal_static_apikey_KeyRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nordstrom.gtm.apikey.KeyRequest.class, com.nordstrom.gtm.apikey.KeyRequest.Builder.class);
  }

  public static final int SERVICE_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object serviceName_;
  /**
   * <code>string service_name = 1;</code>
   */
  public java.lang.String getServiceName() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceName_ = s;
      return s;
    }
  }
  /**
   * <code>string service_name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getServiceNameBytes() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEY_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object keyName_;
  /**
   * <code>string key_name = 2;</code>
   */
  public java.lang.String getKeyName() {
    java.lang.Object ref = keyName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      keyName_ = s;
      return s;
    }
  }
  /**
   * <code>string key_name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getKeyNameBytes() {
    java.lang.Object ref = keyName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      keyName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int THREE_FIELD_NUMBER = 3;
  private volatile java.lang.Object three_;
  /**
   * <code>string three = 3;</code>
   */
  public java.lang.String getThree() {
    java.lang.Object ref = three_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      three_ = s;
      return s;
    }
  }
  /**
   * <code>string three = 3;</code>
   */
  public com.google.protobuf.ByteString
      getThreeBytes() {
    java.lang.Object ref = three_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      three_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FOUR_FIELD_NUMBER = 4;
  private volatile java.lang.Object four_;
  /**
   * <code>string four = 4;</code>
   */
  public java.lang.String getFour() {
    java.lang.Object ref = four_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      four_ = s;
      return s;
    }
  }
  /**
   * <code>string four = 4;</code>
   */
  public com.google.protobuf.ByteString
      getFourBytes() {
    java.lang.Object ref = four_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      four_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIVE_FIELD_NUMBER = 5;
  private volatile java.lang.Object five_;
  /**
   * <code>string five = 5;</code>
   */
  public java.lang.String getFive() {
    java.lang.Object ref = five_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      five_ = s;
      return s;
    }
  }
  /**
   * <code>string five = 5;</code>
   */
  public com.google.protobuf.ByteString
      getFiveBytes() {
    java.lang.Object ref = five_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      five_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIX_FIELD_NUMBER = 6;
  private volatile java.lang.Object six_;
  /**
   * <code>string six = 6;</code>
   */
  public java.lang.String getSix() {
    java.lang.Object ref = six_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      six_ = s;
      return s;
    }
  }
  /**
   * <code>string six = 6;</code>
   */
  public com.google.protobuf.ByteString
      getSixBytes() {
    java.lang.Object ref = six_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      six_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEVEN_FIELD_NUMBER = 7;
  private volatile java.lang.Object seven_;
  /**
   * <code>string seven = 7;</code>
   */
  public java.lang.String getSeven() {
    java.lang.Object ref = seven_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      seven_ = s;
      return s;
    }
  }
  /**
   * <code>string seven = 7;</code>
   */
  public com.google.protobuf.ByteString
      getSevenBytes() {
    java.lang.Object ref = seven_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      seven_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EIGHT_FIELD_NUMBER = 8;
  private volatile java.lang.Object eight_;
  /**
   * <code>string eight = 8;</code>
   */
  public java.lang.String getEight() {
    java.lang.Object ref = eight_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eight_ = s;
      return s;
    }
  }
  /**
   * <code>string eight = 8;</code>
   */
  public com.google.protobuf.ByteString
      getEightBytes() {
    java.lang.Object ref = eight_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eight_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NINE_FIELD_NUMBER = 9;
  private volatile java.lang.Object nine_;
  /**
   * <code>string nine = 9;</code>
   */
  public java.lang.String getNine() {
    java.lang.Object ref = nine_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nine_ = s;
      return s;
    }
  }
  /**
   * <code>string nine = 9;</code>
   */
  public com.google.protobuf.ByteString
      getNineBytes() {
    java.lang.Object ref = nine_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nine_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getServiceNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serviceName_);
    }
    if (!getKeyNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, keyName_);
    }
    if (!getThreeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, three_);
    }
    if (!getFourBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, four_);
    }
    if (!getFiveBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, five_);
    }
    if (!getSixBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, six_);
    }
    if (!getSevenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, seven_);
    }
    if (!getEightBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, eight_);
    }
    if (!getNineBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, nine_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getServiceNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serviceName_);
    }
    if (!getKeyNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, keyName_);
    }
    if (!getThreeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, three_);
    }
    if (!getFourBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, four_);
    }
    if (!getFiveBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, five_);
    }
    if (!getSixBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, six_);
    }
    if (!getSevenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, seven_);
    }
    if (!getEightBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, eight_);
    }
    if (!getNineBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, nine_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nordstrom.gtm.apikey.KeyRequest)) {
      return super.equals(obj);
    }
    com.nordstrom.gtm.apikey.KeyRequest other = (com.nordstrom.gtm.apikey.KeyRequest) obj;

    boolean result = true;
    result = result && getServiceName()
        .equals(other.getServiceName());
    result = result && getKeyName()
        .equals(other.getKeyName());
    result = result && getThree()
        .equals(other.getThree());
    result = result && getFour()
        .equals(other.getFour());
    result = result && getFive()
        .equals(other.getFive());
    result = result && getSix()
        .equals(other.getSix());
    result = result && getSeven()
        .equals(other.getSeven());
    result = result && getEight()
        .equals(other.getEight());
    result = result && getNine()
        .equals(other.getNine());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVICE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getServiceName().hashCode();
    hash = (37 * hash) + KEY_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getKeyName().hashCode();
    hash = (37 * hash) + THREE_FIELD_NUMBER;
    hash = (53 * hash) + getThree().hashCode();
    hash = (37 * hash) + FOUR_FIELD_NUMBER;
    hash = (53 * hash) + getFour().hashCode();
    hash = (37 * hash) + FIVE_FIELD_NUMBER;
    hash = (53 * hash) + getFive().hashCode();
    hash = (37 * hash) + SIX_FIELD_NUMBER;
    hash = (53 * hash) + getSix().hashCode();
    hash = (37 * hash) + SEVEN_FIELD_NUMBER;
    hash = (53 * hash) + getSeven().hashCode();
    hash = (37 * hash) + EIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getEight().hashCode();
    hash = (37 * hash) + NINE_FIELD_NUMBER;
    hash = (53 * hash) + getNine().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nordstrom.gtm.apikey.KeyRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nordstrom.gtm.apikey.KeyRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nordstrom.gtm.apikey.KeyRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nordstrom.gtm.apikey.KeyRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nordstrom.gtm.apikey.KeyRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nordstrom.gtm.apikey.KeyRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nordstrom.gtm.apikey.KeyRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nordstrom.gtm.apikey.KeyRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nordstrom.gtm.apikey.KeyRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nordstrom.gtm.apikey.KeyRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nordstrom.gtm.apikey.KeyRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nordstrom.gtm.apikey.KeyRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nordstrom.gtm.apikey.KeyRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code apikey.KeyRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:apikey.KeyRequest)
      com.nordstrom.gtm.apikey.KeyRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nordstrom.gtm.apikey.ApiKeyProto.internal_static_apikey_KeyRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nordstrom.gtm.apikey.ApiKeyProto.internal_static_apikey_KeyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nordstrom.gtm.apikey.KeyRequest.class, com.nordstrom.gtm.apikey.KeyRequest.Builder.class);
    }

    // Construct using com.nordstrom.gtm.apikey.KeyRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      serviceName_ = "";

      keyName_ = "";

      three_ = "";

      four_ = "";

      five_ = "";

      six_ = "";

      seven_ = "";

      eight_ = "";

      nine_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nordstrom.gtm.apikey.ApiKeyProto.internal_static_apikey_KeyRequest_descriptor;
    }

    public com.nordstrom.gtm.apikey.KeyRequest getDefaultInstanceForType() {
      return com.nordstrom.gtm.apikey.KeyRequest.getDefaultInstance();
    }

    public com.nordstrom.gtm.apikey.KeyRequest build() {
      com.nordstrom.gtm.apikey.KeyRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.nordstrom.gtm.apikey.KeyRequest buildPartial() {
      com.nordstrom.gtm.apikey.KeyRequest result = new com.nordstrom.gtm.apikey.KeyRequest(this);
      result.serviceName_ = serviceName_;
      result.keyName_ = keyName_;
      result.three_ = three_;
      result.four_ = four_;
      result.five_ = five_;
      result.six_ = six_;
      result.seven_ = seven_;
      result.eight_ = eight_;
      result.nine_ = nine_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nordstrom.gtm.apikey.KeyRequest) {
        return mergeFrom((com.nordstrom.gtm.apikey.KeyRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nordstrom.gtm.apikey.KeyRequest other) {
      if (other == com.nordstrom.gtm.apikey.KeyRequest.getDefaultInstance()) return this;
      if (!other.getServiceName().isEmpty()) {
        serviceName_ = other.serviceName_;
        onChanged();
      }
      if (!other.getKeyName().isEmpty()) {
        keyName_ = other.keyName_;
        onChanged();
      }
      if (!other.getThree().isEmpty()) {
        three_ = other.three_;
        onChanged();
      }
      if (!other.getFour().isEmpty()) {
        four_ = other.four_;
        onChanged();
      }
      if (!other.getFive().isEmpty()) {
        five_ = other.five_;
        onChanged();
      }
      if (!other.getSix().isEmpty()) {
        six_ = other.six_;
        onChanged();
      }
      if (!other.getSeven().isEmpty()) {
        seven_ = other.seven_;
        onChanged();
      }
      if (!other.getEight().isEmpty()) {
        eight_ = other.eight_;
        onChanged();
      }
      if (!other.getNine().isEmpty()) {
        nine_ = other.nine_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.nordstrom.gtm.apikey.KeyRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.nordstrom.gtm.apikey.KeyRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object serviceName_ = "";
    /**
     * <code>string service_name = 1;</code>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string service_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string service_name = 1;</code>
     */
    public Builder setServiceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string service_name = 1;</code>
     */
    public Builder clearServiceName() {
      
      serviceName_ = getDefaultInstance().getServiceName();
      onChanged();
      return this;
    }
    /**
     * <code>string service_name = 1;</code>
     */
    public Builder setServiceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object keyName_ = "";
    /**
     * <code>string key_name = 2;</code>
     */
    public java.lang.String getKeyName() {
      java.lang.Object ref = keyName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string key_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getKeyNameBytes() {
      java.lang.Object ref = keyName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string key_name = 2;</code>
     */
    public Builder setKeyName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      keyName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string key_name = 2;</code>
     */
    public Builder clearKeyName() {
      
      keyName_ = getDefaultInstance().getKeyName();
      onChanged();
      return this;
    }
    /**
     * <code>string key_name = 2;</code>
     */
    public Builder setKeyNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      keyName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object three_ = "";
    /**
     * <code>string three = 3;</code>
     */
    public java.lang.String getThree() {
      java.lang.Object ref = three_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        three_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string three = 3;</code>
     */
    public com.google.protobuf.ByteString
        getThreeBytes() {
      java.lang.Object ref = three_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        three_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string three = 3;</code>
     */
    public Builder setThree(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      three_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string three = 3;</code>
     */
    public Builder clearThree() {
      
      three_ = getDefaultInstance().getThree();
      onChanged();
      return this;
    }
    /**
     * <code>string three = 3;</code>
     */
    public Builder setThreeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      three_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object four_ = "";
    /**
     * <code>string four = 4;</code>
     */
    public java.lang.String getFour() {
      java.lang.Object ref = four_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        four_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string four = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFourBytes() {
      java.lang.Object ref = four_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        four_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string four = 4;</code>
     */
    public Builder setFour(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      four_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string four = 4;</code>
     */
    public Builder clearFour() {
      
      four_ = getDefaultInstance().getFour();
      onChanged();
      return this;
    }
    /**
     * <code>string four = 4;</code>
     */
    public Builder setFourBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      four_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object five_ = "";
    /**
     * <code>string five = 5;</code>
     */
    public java.lang.String getFive() {
      java.lang.Object ref = five_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        five_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string five = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFiveBytes() {
      java.lang.Object ref = five_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        five_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string five = 5;</code>
     */
    public Builder setFive(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      five_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string five = 5;</code>
     */
    public Builder clearFive() {
      
      five_ = getDefaultInstance().getFive();
      onChanged();
      return this;
    }
    /**
     * <code>string five = 5;</code>
     */
    public Builder setFiveBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      five_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object six_ = "";
    /**
     * <code>string six = 6;</code>
     */
    public java.lang.String getSix() {
      java.lang.Object ref = six_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        six_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string six = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSixBytes() {
      java.lang.Object ref = six_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        six_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string six = 6;</code>
     */
    public Builder setSix(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      six_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string six = 6;</code>
     */
    public Builder clearSix() {
      
      six_ = getDefaultInstance().getSix();
      onChanged();
      return this;
    }
    /**
     * <code>string six = 6;</code>
     */
    public Builder setSixBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      six_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object seven_ = "";
    /**
     * <code>string seven = 7;</code>
     */
    public java.lang.String getSeven() {
      java.lang.Object ref = seven_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        seven_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string seven = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSevenBytes() {
      java.lang.Object ref = seven_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        seven_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string seven = 7;</code>
     */
    public Builder setSeven(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      seven_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string seven = 7;</code>
     */
    public Builder clearSeven() {
      
      seven_ = getDefaultInstance().getSeven();
      onChanged();
      return this;
    }
    /**
     * <code>string seven = 7;</code>
     */
    public Builder setSevenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      seven_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object eight_ = "";
    /**
     * <code>string eight = 8;</code>
     */
    public java.lang.String getEight() {
      java.lang.Object ref = eight_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eight_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string eight = 8;</code>
     */
    public com.google.protobuf.ByteString
        getEightBytes() {
      java.lang.Object ref = eight_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eight_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string eight = 8;</code>
     */
    public Builder setEight(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      eight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string eight = 8;</code>
     */
    public Builder clearEight() {
      
      eight_ = getDefaultInstance().getEight();
      onChanged();
      return this;
    }
    /**
     * <code>string eight = 8;</code>
     */
    public Builder setEightBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      eight_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nine_ = "";
    /**
     * <code>string nine = 9;</code>
     */
    public java.lang.String getNine() {
      java.lang.Object ref = nine_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nine_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nine = 9;</code>
     */
    public com.google.protobuf.ByteString
        getNineBytes() {
      java.lang.Object ref = nine_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nine_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nine = 9;</code>
     */
    public Builder setNine(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nine_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nine = 9;</code>
     */
    public Builder clearNine() {
      
      nine_ = getDefaultInstance().getNine();
      onChanged();
      return this;
    }
    /**
     * <code>string nine = 9;</code>
     */
    public Builder setNineBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nine_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:apikey.KeyRequest)
  }

  // @@protoc_insertion_point(class_scope:apikey.KeyRequest)
  private static final com.nordstrom.gtm.apikey.KeyRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nordstrom.gtm.apikey.KeyRequest();
  }

  public static com.nordstrom.gtm.apikey.KeyRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KeyRequest>
      PARSER = new com.google.protobuf.AbstractParser<KeyRequest>() {
    public KeyRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new KeyRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<KeyRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KeyRequest> getParserForType() {
    return PARSER;
  }

  public com.nordstrom.gtm.apikey.KeyRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

